template:
  name: my/AI-2.0-flash-001
  purpose: # ここに用途や目的を記述
  temperature: 0.1
  max_tokens: 4096
  timeout: 30
  features:
    - OCR
    - Multilingual
    - Vision
    - Fast
    - Cheap
    # 使用目的別のfeature
    - Code
    - Writing
    - Translation
    - Summarization
    - Search
    - RolePlay
    - Math
    - DeepResearch
    - Voice
    - API

models:
  gem2f-ocr-ja:
    name: google/gemini-2.0-flash-001
    temperature: 0.3
    max_tokens: 2500
    features:
      -Cheap
      -OCR

  gem2f-chat-ja:
    name: google/gemini-2.0-flash-001
    temperature: 0.6
    max_tokens: 10000
    features:
      -Cheap
      -chat
