"""initial migration

Revision ID: 9b75495f844b
Revises: 
Create Date: 2025-07-15 11:12:21.271957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b75495f844b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LLM_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('files_num', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_LLM_outputs_created_at', 'LLM_outputs', ['created_at'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('collection', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('idx_files_collection', 'files', ['collection'], unique=False)
    op.create_index('idx_files_file_type', 'files', ['file_type'], unique=False)
    op.create_index('idx_files_hash', 'files', ['hash'], unique=False)
    op.create_table('LLM_files',
    sa.Column('LLM_output_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LLM_output_id'], ['LLM_outputs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LLM_output_id', 'file_id')
    )
    op.create_index('idx_LLM_files_file_id', 'LLM_files', ['file_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('encoding', sa.Text(), server_default='utf-8', nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('images',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.Text(), nullable=True),
    sa.Column('region_index', sa.Integer(), nullable=True),
    sa.Column('parent_image_id', sa.Integer(), nullable=True),
    sa.Column('mask_image_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('flashcards')
    op.drop_index('idx_LLM_files_file_id', table_name='LLM_files')
    op.drop_table('LLM_files')
    op.drop_index('idx_files_hash', table_name='files')
    op.drop_index('idx_files_file_type', table_name='files')
    op.drop_index('idx_files_collection', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_LLM_outputs_created_at', table_name='LLM_outputs')
    op.drop_table('LLM_outputs')
    # ### end Alembic commands ###
